name: shellcheck

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: bash syntax check
        run: bash -n findgcp-webodm.sh

      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          additional_files: 'findgcp-webodm.sh'
